name: dogger
description: Just a logger ruuning on it's isolate to make logging overheadless.
version: 0.0.1
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  quiver_log: "^1.0.3"
  lookup_map: "^0.0.1"
  uuid: "0.5.0"
  stack_trace: "^1.6.0"
  validator: ">=0.0.4 <0.1.0"
  isodance:
    git: git://github.com/rayk/isodance.git

dev_dependencies:
  coverage: "^0.7.2"
  dart_dev: "^1.0.0"
  dart_style: ">=0.1.8 <0.3.0"
  dartdoc: "^0.4.0"
  test: "^0.12.0"
  quiver: "^0.21.4"
  semver: "^0.2.1"


